AppBundle\Entity\Category:
    properties:
        name:
            - NotBlank: ~
        modifier:
            - NotBlank: { groups: [modify] }
        info:
            - Collection:
                fields:
                    id:
                        - Optional: ~
                    title:
                        - Optional:
                            - NotBlank:
                                groups: [ info ]
                    text:
                        - Optional:
                            - NotBlank: ~
