AppBundle\Entity\Category:
    properties:
        name:
            - NotBlank: ~
        modifier:
            - NotBlank: { groups: [modify] }
        info:
            - Collection:
                fields:
                    id:
                        - Optional: ~
                    title:
                        - AppBundle\Validator\Constraints\NonLatin: { groups: [info] }
