AppBundle\Entity\Category:
    properties:
        name:
            - NotBlank: ~
        modifier:
            - NotBlank: { groups: [modify] }
        info:
            - Collection:
                fields:
                    id:
                        - Optional: ~
                    title:
                        - Optional:
                            - Length:
                                min: 3
                                max: 25
                                groups: [ info ]
